grpc:
  port: 9000
  enabled: true
  enableReflection: true

  netty-server:
    keep-alive-time: 30s
    max-inbound-message-size: 10MB
    primary-listen-address: 127.0.0.1:9000
    additional-listen-addresses:
      - 127.0.0.1:10000
    on-collision-prefer-shaded-netty: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt-generation:
    type: Bearer
    key: d9de27c3-ad05-4401-8813-521a02996834
    validity: 25920000000
    issuer: user-management-service
    audience: anyone.com

logging:
  level:
    root: info
